### PR TITLE
16.0.0 support

### PR DESCRIPTION
**Pull request by FlyingBananaTree**

### CODE REVIEW

**Comment by friedkeenan** [comment]
I'll probably merge this once Atmosphere gets updated and you or someone else is able to verify that this works. Thank you!

**Comment by friedkeenan** [comment]
Awesome, thanks for the contribution

**Comment by GOKUAKU** [comment]
custom logos don´t work on 16.0.0

**Comment by friedkeenan** [comment]
I've received no other reports of it not working despite 16.0.0 existing for quite a while. Can you describe exactly what behavior you're experiencing? And what you do to acquire an install the patches?

**Comment by GOKUAKU** [comment]
Up to 15.0.0, I could use it.
From 16.0.0, it suddenly grabbed and became unusable.
The following is the environment in which I created this time.

OS:win11 Pro
 python-3.10.6-amd64

atmosphere
 - exefs_patches
  - logo1
   -  IPS (422KB) 18  file

**Comment by GOKUAKU** [comment]
Up to 15.0.0, I could use it.
From 16.0.0, it suddenly grabbed and became unusable.
The following is the environment in which I created this time.

OS:win11 Pro
 python-3.10.6-amd64

atmosphere
 - exefs_patches
 　 - logo1
   　-  IPS (422KB) 18  file

**Comment by GOKUAKU** [comment]
Up to 15.0.0, I could use it.
From 16.0.0, it suddenly grabbed and became unusable.
The following is the environment in which I created this time.

OS:win11 Pro
 python-3.10.6-amd64

atmosphere
　 - exefs_patches
  　　- logo1
 　　　  -  IPS (422KB) 18  file

**Comment by GOKUAKU** [comment]
Up to 15.0.0, I could use it.
From 16.0.0, it suddenly grabbed and became unusable.
The following is the environment in which I created this time.

OS:win11 Pro
python-3.10.6-amd64

atmosphere
　 - exefs_patches
　　- logo1
　　　 - IPS (422KB) 19 file

**Comment by friedkeenan** [comment]
I noticed you recommented this a couple times. Do note that you can edit comments. Of note, I noticed that you previously listed that there were 18 patches, but now it's 19. It still does not work for you? Because I myself just verified that the patch offset is correct for 16.0.0. I haven't booted 16.0.0, but it should work fine.

**Comment by GOKUAKU** [comment]
Thank you for your guidance.
I will try many things.

**Comment by GOKUAKU** [comment]
I re-installed Atmosphere or hekate and it worked fine.
Thank you very much.

**Pull request merged**
