### PR TITLE
Update for 13.0.0

### LINKED ISSUE #8: Support 13.0.0
Please add support for OFW 13.0.0. Thank you

### PR DESCRIPTION
**Pull request by 16BitWonder**
Should close #8.

### CODE REVIEW

**Comment by friedkeenan** [comment]
I'm unable to test/confirm this atm, though if you confirm that you've tested that it works on 13.0.0, I'll happily merge this

**Comment by Skonikol** [comment]
> I'm unable to test/confirm this atm, though if you confirm that you've tested that it works on 13.0.0, I'll happily merge this

I confirm that it works (ams 1.1.0, ofw 13.0.0, lite, emuMMC)

**Comment by friedkeenan** [comment]
Cool, thank you both

**Comment by Hernie22** [comment]
I'm not going to lie, i'm new at this, but i'm getting a syntax error when i run the newest 13.0.0 script.

PS C:\Switch\Homebrew\Themes\Boot Logos> py gen_patches.py output mario_logo.dds
  File "C:\Switch\Homebrew\Themes\Boot Logos\gen_patches.py", line 111
    <title>switch-logo-patcher/gen_patches.py at master · friedkeenan/switch-logo-patcher · GitHub</title>
                                                        ^
SyntaxError: invalid character '·' (U+00B7)

I appreciate all that you do. I wish i had the skills to do this.

**Pull request merged**
